### ISSUE TITLE
Add Daily todo section to Planner View

### ISSUE THREAD

**Issue by wpendl99** [wpendl99/High-Performance-Planner#2]
Make it so that:

- [x] 1. The tasks don't look weird (remove the rounded border)
- [x] 2. You add a new on at the bottom of the list not the middle
- [x] 3. Make it so that the header for the Task Section is colored? (Maybe make a task to change color preferences in a settings view) - I didn't want that anymore
- [x] 4. Fix newTaskDescription not clearing the new task data after you create a new task

**Comment by wpendl99** [comment]
I fixed 1 by removing rounded border

**Comment by wpendl99** [comment]
I fixed 2. I am canceling 3. I want to make it 1 section and then I added colored dots to help with categorization. I fixed 4.

**Comment by wpendl99** [comment]
Fix the Today's Todos to:

- [ ] 1) be able to undo completing a task
- [x] 2) Show color dot in menu select for categories
- [x] 3) make it so the last category you selected (when you changed any task) is that next category for the next new task
- [ ] 4) Add info button
- [x] 5) Make it so tap and hold allow you to drag and drop task 
- [ ] (BONUS: Make it so you can move take to and from Things to keep and mind and today's todos) For the bonus
